### ISSUE TITLE
Unable to Run AppImages without appimagelauncher Installed or binfmt-bypass

### ISSUE THREAD

**Issue by nazdridoy** [ivan-hc/APPLICATION-MANAGER#107]
### Issue Summary

I'm encountering difficulties running AppImages without having appimagelauncher installed. Whenever I attempt to run an AppImage, I receive an error message stating "no such file or directory," even though I can visibly see the file in question. Interestingly, I found that if I have a copy of /usr/lib/appimagelauncher/binfmt-bypass from appimagelauncher, I can successfully run the AppImages using the command ./binfmt-bypass demo.appimage.

### Steps to Reproduce

1. Try running an AppImage without appimagelauncher installed.
2. Observe the error message indicating "no such file or directory."

## Environment

- **Operating System:** Archlinux

## Additional Information

![2024-01-19_04-14](https://github.com/ivan-hc/AM-Application-Manager/assets/45564804/d394d6b4-ffd7-44e1-bbf8-3d345e0e5f93)

**Comment by ivan-hc** [comment]
Have you installed it using AppMan?

This may be a duplicated of https://github.com/ivan-hc/AppMan/issues/25 and https://github.com/ivan-hc/AppMan/issues/26

In brief you should check your `~/.profile` and `~/.bashrc` file to put `~/.local/bin` at the end of `echo $PATH` (I don't know what to do about ZSH)

**Comment by ivan-hc** [comment]
is this happening only with obsidian or with all other appimages?

**Comment by ivan-hc** [comment]
I suppose that you're using a minimal DE or just a WM with as less packages installed as possible. Isn't it?

**Comment by ivan-hc** [comment]
is fuse2 or fuse3 installed?

**Comment by ivan-hc** [comment]
have you tried to revert the order of $PATH in your ~/.profile file?
```
sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' $HOME/.profile
```
from the screenshot it seems not

**Comment by ivan-hc** [comment]
I've never seen so many paths into a `echo $PATH`

However, you must edit your ~/.profile.

If it is not available, add this at the end of the file:
```
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$PATH:$HOME/.local/bin"
fi
```
this is my ~/.profile file
```
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$PATH:$HOME/.local/bin"
fi
```
it is a priority over ~/.bashrc

**Comment by ivan-hc** [comment]
I don't really know why all this happens.

**Comment by ivan-hc** [comment]
How you install/use it? Give me as much info as possible and I'll tri to implement it somewhere.

Now I go sleep, its 7 am here. I'll read it later.

**Comment by ivan-hc** [comment]
I would test this, if you have installed `binutils` and `tar`, do:
```
wget https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher_2.2.0-travis995.0f91801.xenial_amd64.deb
ar x appimagelauncher_2.2.0-travis995.0f91801.xenial_amd64.deb
tar fx tar fx data.tar.xz
```
then
```
export LD_LIBRARY_PATH=/path/to/usr/lib/x86_64-linux-gnu/appimagelauncher/:"${LD_LIBRARY_PATH}"
```
then try to exec a program and tell me if this works for you

**Comment by ivan-hc** [comment]
so it works without the daemo... interesting.

If @TheAssassin authorizes me, I could write an option in AM to solve the problem using his libraries

**Comment by ivan-hc** [comment]
is `binfmt-bypass` a standalone binary that works without `libbinfmt-bypass-preload.so` or needs it?

**Comment by TheAssassin** [comment]
You need both. The preload library is injected by `binfmt-bypass` into the target AppImage using `LD_PRELOAD`.

**Comment by TheAssassin** [comment]
That said, why do you need to worry about these at all anyway? If you want to suppress AppImageLauncher ('s GUI) you can just export an environment variable.

**Comment by TheAssassin** [comment]
Have you ever had installed AppImageLauncher? Then it might be some leftover `binfmt_misc` configuration.

```sh
> cat /proc/sys/fs/binfmt_misc/appimage-type*
enabled
interpreter /usr/lib/x86_64-linux-gnu/appimagelauncher/binfmt-interpreter
flags: F
offset 8
magic 414901
enabled
interpreter /usr/lib/x86_64-linux-gnu/appimagelauncher/binfmt-interpreter
flags: F
offset 8
magic 414902

**Comment by ivan-hc** [comment]
@TheAssassin its exactly what I was thinking about, maybe...
```
echo 'export LD_LIBRARY_PATH=/path/to/usr/lib/x86_64-linux-gnu/appimagelauncher/:"${LD_LIBRARY_PATH}"' >> $HOME/.bashrc
echo 'export LD_PRELOAD=/path/to/usr/lib/x86_64-linux-gnu/appimagelauncher/binfmt-bypass' >> $HOME/.bashrc
```
is this correct?

**Comment by TheAssassin** [comment]
@ivan-hc if they do not intend to use AppImageLauncher, there is no reason to worry about `binfmt-bypass`. I think you may not have entirely understood yet what it is good for. It is _just_ needed with AppImageLauncher's _own_ binfmt-bypass rules, which should not be active if AppImageLauncher is not installed.

@nazdridoy for a quick test, I suggest you disable binfmt_misc temporary using `sudo systemctl stop systemd-binfmt.service`.

You may have to reboot to get rid of those rules if you had AppImageLauncher installed in the meantime. While systemd's binfmt_misc integration enables new rules very quickly, it doesn't recognize that the configuration files were deleted and thus does not remove those rules. If you do not want to reboot and are on Debian, you can use `sudo update-binfmts --disable appimage-type2` and `sudo update-binfmts --disable appimage-type1` to disable them until you reboot.

**Comment by ivan-hc** [comment]
@nazdridoy I've not understood, was it the active service that prevented you from running the Appimages?

**Comment by TheAssassin** [comment]
@ivan-hc re-reading https://github.com/ivan-hc/AM-Application-Manager/issues/107#issuecomment-1901093586, I suggest you remove those comments. They are quite misleading and could cause people more harm than good. As said, binfmt-bypass is a component only AppImageLauncher itself should ever use directly. That's why it's not exposed to the user but "hidden" in `/usr/lib`.

>  was it the active service that prevented you from running the Appimages?

It was a left-over from a previous AppImageLauncher installation paired with a user who clearly doesn't know the internals of AppImageLauncher (who I don't blame for that, by the way, you shouldn't need to know). Most of the discussion was leading away from the first fact, leading to you chasing red herrings.

**Comment by ivan-hc** [comment]
@TheAssassin simply thank you for the help. I'm glad you joined the conversation and solved the problem.

@nazdridoy Moral of the story: when "the software is provided as is", there is no point in beating around the bush trying to pick bits and pieces to solve your problems. You would only cause trouble.
